export const commentBank = {
  math: {
    SEL: {
      '1-1': '*N* is gaining confidence in trying mathematical challenges and has focused on developing *R* problem solving skills this term. *N* makes connections, and relates mathematical ideas to situations drawn from other contexts (e.g., daily life, sports). *N* communicates mathematical thinking orally, visually, and in writing, using everyday language and some mathematical vocabulary.',
      '2-1': '*N* is gaining confidence in trying mathematical challenges and has focused on developing *R* problem solving skills this term. *N* makes connections, and relates mathematical ideas to situations drawn from other contexts (e.g., daily life, sports). *N* communicates mathematical thinking orally, visually, and in writing, using everyday language and some mathematical vocabulary.',
      '3-1': '*N* develops reasonable plans to solve problems and explain *R* thinking. *N* creates a variety of representations of mathematical ideas (e.g., by using physical models, pictures, numbers, variables, graphs), makes connections among them, and applies them to solve new problems.',
      '4-1': '*N* is an engaged participant who comfortably explores the mathematical process and rises to new challenges in mathematics. *P* demonstrates when *P* is reflecting on and monitoring *R* thinking to help clarify *R* understanding as *P* solves a problem (e.g., by comparing and adjusting strategies used).',
      'incomplete-1': '',
    },
    Operations: {
      '1-1': '*N* is developing fluency in *R* ability to divide 2 digit and 3 digit whole numbers. *P* is often able to solve for missing numbers in simple word problems, and communicates an understanding of the relationship between multiplication and division.*N* is beginning to use the organizational strategy of the area model to support *R* exploration of multiplication to multiply two digit by two digit numbers. *N* is learning mental math strategies and is encouraged to practice *R* multiplication tables to 12x12. *N* is encouraged to continue practicing using organizational strategies to solve two by two digit multiplication (ie. area model).',
      '2-1': '*N* is gaining new confidence in *R* ability to divide 2 digit and 3 digit whole numbers. *P* is often able to solve for missing numbers in simple multiplication and division number or word problems, showing an understanding of the relationship between multiplication and division.*N* is confident with *R* use of organizational strategies such as the area model to support *R* exploration of multiplication with two digit by two digit numbers.',
      '3-1': '*N* can confidently compute single standard digit multipliers using mental math strategies and demonstrates a new confidence in *R* ability to divide 2 digit and 3 digit whole numbers. *P* is able to solve for missing numbers in simple multiplication and division number or word problems, showing an understanding of the relationship between multiplication and division. *N* has shown a budding confidence in *R* multiplication tables to 12x12 and is able to apply organizational strategies such as the area model or algorithm to support *R* exploration of multiplication with two by two and three by two digit numbers',
      '4-1': '*N* demonstrates improvement with the recall of *R* times tables to 12X12 using mental math strategies. *P* has mastered multiplying any number up to 4 digits by 10, 100 or 1000, using knowledge of place value. *N* is able to divide 3 digit numbers with ease, and is very comfortable using an area model strategy or algorithm to organize multiplication of 3 by 2 digit numbers. *P* can explain the relationship between multiplication and division as well as solve for missing products or quotients in multiplication and division questions.',
      'incomplete-1': '',
    },
    Spatial: {
      '1-1': '*N* is able to categorize angles in objects around the classroom (ie. the corner of his desk, the tip of his pizza). By matching angles and side measurements, *P* can identify and create congruent triangles, rectangles, and parallelograms. *N* is working toward independence in the use of a protractor to measure and create congruent angles in a variety of figures. *P* has developed new confidence in describing and performing reflections, and is working toward performing translations and rotations about a specific point with the use of hands-on materials.',
      '2-1': '*N* can describe the size of an angle, by comparing it to more familiar angles like right angles. *N* is working toward making effective use of a protractor to measure and create congruent angles in a triangle. *N* is able to perform translations and reflections. *P* is working toward performing rotations about a specific point. *R* next step will be to apply angle properties to solve for unknown angle measures.',
      '3-1': '*N* can accurately describe and create a specific angle, identify and create congruent triangles, solve for a missing angle and make effective use of a protractor. *N* describes and performs translations and reflections and is working toward performing rotations consistently about a specific point.',
      '4-1': '*N* can accurately describe the size of an angle, identify and create congruent triangles, solve for a missing angle and make effective use of a protractor. *N* describes and performs translations and reflections and performs rotations consistently about a specific point.',
      'incomplete-1': '',
    },
    Algebra: {
      '1-1': '*N* is encouraged to use an open number line to record, organize and justify *R* pre-algebra thinking. To build *R* understanding of equations and inequalities, including missing variables, *N* is encouraged to look for real world examples.',
      '2-1': '*N* is encouraged to use an open number line to record, organize and justify *R* pre-algebra thinking. To build *R* understanding of equations and inequalities, including missing variables, *N* is encouraged to look for real world examples.',
      '3-1': '*N* is encouraged to continue using an open number line to record, organize and justify *R* mathematical thinking and solve for unknown variables. To build further fluency, *N* is encouraged to proactive *R* multiplication facts up to 12 through games such as those from class (ie. Multiplication squares, online learning)',
      '4-1': '*N* can confidently write equations and word problems to show how two amounts are related including equations that use variables to represent quantities. *N* is encouraged to continue engaging with mathematical processes over the summer, and discovering math outside of the classroom',
      'incomplete-1': '',
    }
  },
  language: {
    'Transferable Skills': {
      '1-1': '*N* is learning how to make use of the elements of style and conventions. *P* is creating short writing pieces and oral presentations that *R* audience finds interesting.',
      '2-1': '*N* is learning how to make use of the elements of style and conventions. *P* is creating short writing pieces and oral presentations that *R* audience finds interesting.',
      '3-1': '*N* effectively uses strategies to increase comprehension during reading (e.g. summarizing) and listening (e.g. annotating) activities. *P* uses the elements of style and conventions to create engaging oral presentations this term, and has shown progress in creating *R* own texts.',
      '4-1': '*N* effectively uses a wide variety of strategies to increase comprehension during reading (e.g. summarizing) and listening (e.g. annotating) activities. *P* uses the elements of style and conventions to create writing pieces and oral presentations for *P* audience.',
      'incomplete-1': '',
    },
    Opinion: {
      '1-1': '*N* is working towards communicating *R* ideas, answers and opinions with clarity, and make relevant connections to the ideas of others or content that is read aloud.',
      '2-1': '*N* is working towards communicating *R* ideas, answers and opinions with clarity, and make relevant connections to the ideas of others or content that is read aloud.',
      '3-1': '*N* shares answers and opinions with building confidence, and makes connections to stories or text that is read aloud.',
      '4-1': '*N* demonstrates a refined ability to communicate in a clear, coherent manner, presenting ideas, opinions, and information.',
      'incomplete-1': '',
    },
    'Research + Reporting': {
      '1-1': '*N* experiments with digital tools (e.g., Book Creator, Google slides) to publish written work and communicate inquiry-based learning with some effectiveness. *N* is encouraged to refine their research methods by following timetines and expectations provided.',
      '2-1': '*N* experiments with digital tools (e.g., Book Creator, Google slides) to publish written work and communicate inquiry-based learning with some effectiveness. *N* is encouraged to refine their research methods by following timetines and expectations provided.',
      '3-1': '*N* leverages digital tools to create media texts (e.g., Book Creator, Google Slides, Canva). *P* is working towards producing media pieces to convey research concisely and effectively.',
      '4-1': '*N* produces media pieces with a clear message and understands how design elements (ie. Book Creator, Google Slides, Canva) can help grab the readers’ attention and convey research concisely.',
      'incomplete-1': '',
    },
    Reading: {
      '1-1': '*N* has made progress in *R* reading decoding skills over the first term. *P* is working towards confidently reading high frequency words or classroom terminology and uses the strategies to segment sounds and read unfamiliar words.',
      '2-1': '*N* has made progress in *R* reading decoding skills over the first term. *P* is working towards confidently reading high frequency words or classroom terminology and uses the strategies to segment sounds and read unfamiliar words.',
      '3-1': '*N* uses a variety of comprehension strategies when reading. *P* can readily extend *R* understanding of texts by connecting the ideas in them to *R* own knowledge, experience, and insights and by making inferences.',
      '4-1': '*N* fluently reads a variety of fiction and non-fiction texts and demonstrates a complete understanding of what *P* reads by restating information and connecting ideas to *R* own insights and experiences.',
      'incomplete-1': '',
    },
    Writing: {
      '1-1': '*N* is able to use text features to support *P* comprehension of informational passages. *N* is encouraged to write in full sentences when forming paragraphs as well as use the anchor charts and success criteria available to write effectively. *N* is learning to brainstorm ideas about a topic before *P* writes and is learning to go through the writing process. *N* is beginning to expresses *R* ideas clearly when writing and generate *R* own ideas in persuasive writing.',
      '2-1': '*N* is able to use text features to support *P* comprehension of informational passages. *N* is encouraged to write in full sentences when forming paragraphs as well as use the anchor charts and success criteria available to write effectively. *N* is learning to brainstorm ideas about a topic before *P* writes and is learning to go through the writing process. *N* is beginning to expresses *R* ideas clearly when writing and generate *R* own ideas in persuasive writing.',
      '3-1': '*N* is able to identify text features and use them to comprehend informational texts. *N* writes in full sentences and is able to use anchor charts and success criteria to write specific forms effectively. *N* recognizes how specific strategies can support them through the writing process (e.g., brainstorming, graphic organizers, etc), and *N* expresses *R* ideas clearly when writing.',
      '4-1': '*N* attends to punctuation and text features when reading, allowing *R* to read and present with both fluency and expression. *P* uses text features effectively to comprehend informational texts. *N* writes in complete paragraphs and is able to use anchor charts and success criteria to write specific forms effectively. When writing, *N* can generate ideas and gather information. *P* is able to sort and classify these ideas and information as seen in *R* descriptive and narrative writing.',
      'incomplete-1': '',
    },
    'Comprehension + Critical Thinking': {
      '1-1': '*N* can read and comprehend simple sentences, using knowledge of words, grammar, and background knowledge. *N* is working towards making inferences using stated and implied information and ideas to understand simple texts with consistency. *N* can explain how images, graphics, and pictures create, communicate, and contribute to meaning in stories of interest to *R*.',
      '2-1': '*N* uses *R* own personal experiences to make connections to text read aloud, and is able to make inferences about what the characters may be feeling and predict what may happen next in a story. *P* demonstrates the capability to evaluate relevant topics such as diversity, inclusion, and accessibility in both text and media forms, and is encouraged to reflect on the relevance of these topics at a school level.',
      '3-1': '*N* is able to reflect on *R* reading, and can identify strategies that help them before, during, and after reading. *N* can analyze various texts, including literary and informational texts, by identifying main and supporting ideas. *P* is able to brainstorm and evaluate relevant topics such as diversity, inclusion, and accessibility in both text and media forms.',
      '4-1': '*N* can explain how images, graphics, and visual design create, communicate, and contribute to meaning in a variety of texts. *N* can explain how various topics, such as diversity, inclusion, and accessibility, are addressed in texts and media, as well as articulate what insights or messages are conveyed.*N* frequently uses strategies, such as rereading, visualizing, and asking questions to extend *R* own learning.',
      'incomplete-1': '',
    },
    'Next Steps': {
      '1-1': 'When reading aloud, *N* is encouraged to be more expressive and use appropriate pacing to convey meaning. *N* has demonstrated growth in *R* ability to decode new words.  As a next step, *N* needs to read aloud more frequently, and practice breaking words into smaller parts to begin reading more complex passages of text.',
      '2-1': '*N* is encouraged to organize details and describing words to *R* writing. *N* would benefit from keeping a journal this summer to create pieces of writing using a variety of sentence styles that range from simple to more complex.',
      '3-1': '*N* is encouraged to explore new and exciting forms of text to read aloud at home. To further build on new progress made this year, *N* would benefit from engaging in discussions about stories at home, such as predicting events, examining perspective or writing fun alternative endings to stories.',
      '4-1': 'This summer, *N* is encouraged to explore new, challenging and diverse forms of text that interest *P*. *N* would benefit from continued use of literacy skills at home, and is encouraged to engage in digital writing practices through a journaling routine or use story building tools.',
      'incomplete-1': '',
    },
  },
  science: {
    SEL: {
      '1-1': '*N* is beginning to demonstrate an understanding of how the scientific research process can be applied to investigate changes in matter as well as renewable and non-renewable sources of energy. With support, *N* is able to engage in project-based learning by collecting, organizing, testing and sharing what *P*’s discovered',
      '2-1': '*N* is beginning to demonstrate an understanding of how the scientific research process can be applied to investigate changes in matter as well as renewable and non-renewable sources of energy. With support, *N* is able to engage in project-based learning by collecting, organizing, testing and sharing what *P*’s discovered',
      '3-1': '*N* demonstrates an interest in applying a scientific research process to investigate changes in matter as well as renewable and non-renewable sources of energy. Through collaborative investigations, *N* takes on an active role to support the design of project-based learning.',
      '4-1': '*N* applies a scientific research process to investigate changes in matter as well as renewable and non-renewable sources of energy. Through collaborative investigations, *N* took on a leadership role to support the design of project-based learning.',
      'incomplete-1': '',
    },
    'Conservation of Energy': {
      '1-1': 'In *R* study of Conservation of Energy, *N* is discovering the effects of energy and resource use on society and the environment, and suggests options for conserving energy and resources based on *R* own experiences. At home, *N* is encouraged to apply what *P* has learned about energy conservation at home (e.g., turning off the lights).',
      '2-1': 'In *R* study of Conservation of Energy, *N* is discovering the effects of energy and resource use on society and the environment, and suggests options for conserving energy and resources based on *R* own experiences. At home, *N* is encouraged to apply what *P* has learned about energy conservation at home (e.g., turning off the lights).',
      '3-1': '*N* is able to analyze social and environmental impacts of resource consumption and assesses ways to reduce these impacts in their own life and school community. Through *P* recent Relay Education Solar Workshop, *N* demonstrates an ability to turn hands-on activities into personal connections.',
      '4-1': 'In *R* study of Conservation of Energy, *N* analyzes the long-term impacts of human uses of energy and natural resources on society and the environment, including climate change. *P* accurately describes ways in which individuals can reduce energy consumption, and is encouraged to apply what *P* has learned about energy conservation to make personal impacts that can begin at home (e.g., reducing water consumption).',
      'incomplete-1': '',
    },
    'Structures/Mechanisms': {
      '1-1': '*N* is also beginning to demonstrate an emerging knowledge of internal and external forces that act on structures. This term, *N* applied *P* digital creativity to demonstrate understanding of the relationship of natural external forces to human-made structures in the form of an oral presentation. With support, *N* conducted research and made personal connections to case studies, in order to predict how a structure can become impacted and then withstand forces that may act on it.',
      '2-1': '*N* is also beginning to demonstrate an emerging knowledge of internal and external forces that act on structures. This term, *N* applied *P* digital creativity to demonstrate understanding of the relationship of natural external forces to human-made structures in the form of an oral presentation. With support, *N* conducted research and made personal connections to case studies, in order to predict how a structure can become impacted and then withstand forces that may act on it.',
      '3-1': '*N* also demonstrates an emerging knowledge of internal and external forces that act on structures. This term, *N* applied *P* digital creativity to demonstrate understanding of the relationship of natural external forces to human-made structures in the form of an oral presentation. Through research, case studies in class and personal connections, *N* demonstrates a new understanding of how various structures can become impacted and then withstand forces as they are applied.',
      '4-1': '*N* also demonstrates a practical understanding of forces that act on structures. Through real-world examples, *P* investigates the social and environmental impacts of internal and external forces acting on various structures, by assessing ways to reduce these impacts through material and digital design. In *P* oral presentation of a natural external force, *N* demonstrated *P* can effectively describe natural forces acting on structures, as well as select building materials based on purpose. *N* applies digital creativity in the form of a self-directed infographic effectively, demonstrating an ability to summarize research in a concise and organized manner.',
      'incomplete-1': '',
    },
    'Matter and Energy': {
      '1-1': 'Bad job! Level 1 Matter and Energy!',
      '2-1': 'In both hands-on and minds-on investigations, *P* can describe the three states of matter, and provide an example of each. Using movement and body-connections, *N* can identify common changes of states in matter and describe an example *P* has observed in class. *N* is learning to articulate the differences between physical and chemical changes (e.g., reversible, irreversible), by making real-life connections. *N*’s understanding is evident in *R* digital work and through in-class discussions with peers.',
      '3-1': 'Through a variety of hands-on, minds-on investigations, *P* can describe the three states of matter, explain changes of states in matter and provide examples of each of these changes. *N* also identifies indicators of a chemical change and can articulate the differences between physical and chemical changes (e.g., reversible, irreversible). *N*’s understanding is evident in *R* written work and through in-class discussions with peers.',
      '4-1': 'During our recent study of matter, *N* demonstrates a firm understanding of the properties of matter, changes of state, as well as physical and chemical changes. *N* is able to create and extend concepts from class with connections to text, world, and self. Extension of knowledge is evident in *N*’s application of vocabulary in discussion-based learning as well as connections *P* makes when participating in the scientific process.',
      'incomplete-1': '',
    },
    'Next Step': {
      '1-1': '*N* is encouraged to continue researching connections between class conversations and the world around *R*.',
      '2-1': '*N* is encouraged to explain *P* thinking using vocabulary from class and extending *R* interests in science to everyday discussions.',
      '3-1': '*N* is encouraged to conduct self-directed research with independence and to engage in the scientific process, as this will allow *P* to organize the process of scientific investigation.',
      '4-1': 'At home and in the community, *N* is encouraged to apply the scientific method to observations and wonderings of these topics in daily life, and continue engaging in *R* curiosity for science!',
      'incomplete-1': '',
    },
  },
  'learning skills': {
    'Responsability - Behaviour Reminders': {
      'E-1': 'As grade 6 begins, *N* takes responsibility for and manages *R* own behaviour. *P* follows class and school rules at all times with no need for reminders.',
      'G-1': 'As grade 6 begins, *N* takes responsibility for and manages *R* own behaviour. *P* follows the class and school rules consistently, admitting mistakes and accepting consequences when necessary.',
      'S-1': 'As grade 6 begins, *N* takes responsibility for and manages *R* own behaviour at times. *R* attempts to follow the class and school rules is evident but lack consistency. *N* is encouraged to admit mistakes and accept the consequences, then move forward with more positive choices.',
      'N-1': 'As grade 6 begins, *N* has difficulty taking responsibility for and managing *R* own behaviour. Frequent reminders are needed for *H* to follow the class and school rules with success. *P* is encouraged to admit mistakes and accept the consequences, then move forward with more positive choices.',
    },
    'Responsability - Listening Focus': {
      'E-1': '*N* demonstrates active listening during instructional times without any need for redirection.',
      'G-1': '*N* listens carefully during instructional times without needing redirection.',
      'S-1': '*N* listens during instructional times but not immediately. Stopping activities right away to listen to instructions would be helpful.',
      'N-1': '*N* struggles to listen during instructional times and often needs to be redirected. Stopping activities right away to listen and removing distractions would be helpful.',
    },
    'Responsability - Agenda Deadlines': {
      'E-1': '*N* demonstrates responsibility by effectively keeping track of work and important dates. *H* completes all *R* work with great care and attention to detail, meeting all deadlines.',
      'G-1': '*N* demonstrates responsibility by keeping track of work and important dates. *H* completes *R* work with care and meets most deadlines.',
      'S-1': '*N* demonstrates some responsibility when *P* completes *R* work with care, meeting some deadlines with frequent reminders. *N* is encouraged to more effectively ensure *P* knows what *P* needs to do each day to complete work on time.',
      'N-1': '*N* rarely meets deadlines and work is submitted with little care and attention to detail. *N* is encouraged to use *R* notes and Hapara at home and school to keep track of assignments and deadlines.',
    },
    'Responsability - Class Jobs': {
      'E-1': '*N* has begun demonstrating a commitment to fulfilling *R* class job every day as well as helping others in a Grade 6 leadership role. *H* needs no reminders to complete *R* responsibilities in the class and school.',
      'G-1': 'Since the year has begun, *N* has been committed to fulfilling *R* leadership roles. *H* needs few reminders to complete *R* responsibilities in the classroom, and is beginning to meet the expectations of a Grade 6 role model at school.',
      'S-1': 'This fall, *N* has been willing to help with class jobs when asked. With reminders needed, *P* is able to complete *R* responsibilities in the classroom. *N* is encouraged to look for simple ways *H* can be helpful within the classroom and carry out these tasks as well as monitor *R* individual responsibilities without reminders from others.',
      'N-1': 'In our first months of Grade 6, *N* has needed to be asked frequently to help with essential class jobs and expectations. *H* struggles to complete *R* responsibilities in the classroom even with reminders. *N* is encouraged to look for simple ways *H* can be helpful within the classroom and carry out these tasks as the year progresses.',
    },
    'Independent Work - Distractibility/Completion': {
      'E-1': '*N* works independently during class time in both shared and independent work. *H* remains on-task during work periods, needing no reminders to stay focused, and completes all the expected work in the given time.',
      'G-1': '*N* works independently during class time in both collaborative and independent work. *H* generally remains on-task and needs minimal reminders to stay focused, completing an appropriate amount of work in the given time.',
      'S-1': '*N* needs assistance to begin or transition between activities, but is then able to work independently. *H* needs occasional reminders to remain on task, completing some of the expected work in a given time. *N* is encouraged to use strategies such as choosing to move away from distractions when necessary.',
      'N-1': '*N* struggles to work independently during class time. Often, *P* needs to be redirected multiple times to remain on-task during a single block, and completes little of the expected work in the given time. *N* is encouraged to use strategies such as listening very carefully to instructions, using visual aids as reminders and choosing to move away from distractions when necessary.',
    },
    'Independent Work - Time management/Revision': {
      'E-1': 'When working independently, *N* uses class time effectively. *P* makes a plan and adjusts it as necessary to achieve maximum success. When finished, *P* carefully looks over *R* work for ways to improve.',
      'G-1': 'When working independently, *N* uses class time well. *P* makes a plan and at times adjusts it as necessary to achieve success. When finished, *P* looks over *R* work for ways to improve.',
      'S-1': 'When working independently, *N* uses class time well. *P* makes a simple plan and carries it out to work toward achieving success. However, when *P* finishes *P* needs reminders to look over *R* work for ways to improve. *N* is encouraged to make adjustments to *R* plan when necessary in order to maximize success.',
      'N-1': 'When working independently, *N* uses class time with limited effectiveness. *P* needs help making a simple plan and support in carrying it out with ample reminders or breaks. *N* is encouraged to look over *R* work carefully to find ways to improve it before submission.',
    },
    'Independent Work - LISTENING QUESTIONING': {
      'E-1': '*N* listens carefully to all instructions, ensuring *P* fully understands them. *P* considers what *P* needs to do to complete the task and asks specific questions to ensure *R* success.',
      'G-1': '*N* listens to instructions, making sure *P* understands them with minimal support. *P* thinks about what *P* has to do to successfully complete the task and is beginning to ask questions to ensure *P* is fully prepared.',
      'S-1': '*N* generally listens to instructions but does not always make sure *P* understands them. *N* is encouraged to actively think about what *P* has to do and ask questions to ensure *P* is fully prepared to begin the task. This should help *H* follow through and complete the task with success.',
      'N-1': '*N* needs to make sure *P* understands what to do and has received all instructions before beginning a task. *P* is encouraged to actively think about what *P* has to do and ask questions to ensure *P* is fully prepared to begin most given tasks. This should help *H* follow through and complete work with success. Furthermore, *N* is encouraged to stop, look and listen when lessons are being delivered or when *P* cannot be given frequent and direct reminders to stay on task.',
    },
    'Initiative - Positive attitude': {
      'E-1': '*N* approaches new activities with a positive attitude and a great interest in learning. *P* is willing to take risks when necessary to push *H*self further.',
      'G-1': '*N* approaches new activities with a positive attitude. *P* is encouraged to take more risks to raise *R* comfort level in all subject areas.',
      'S-1': '*N* continues to approach new activities in subject areas of personal growth with hesitation. *P* is encouraged to push *H*self beyond *R* comfort level in new learning situations.',
      'N-1': '*N* continues to approach new activities with hesitation. *P* is encouraged to push *H*self beyond *R* comfort level in new learning situations in order to grow.',
    },
    'Initiative - Advocacy': {
      'E-1': `*N* always takes the initiative to ask for any help when needed and for any work that *P* has missed. In addition, *N* helps others whenever needed in appropriate ways by making sure classmates' needs are also met.`,
      'G-1': `*N* takes the initiative to ask for help when needed and for work that *P* has missed. *N* also is willing to help classmates' to make sure they have help when needed.`,
      'S-1': '*N* sometimes takes the initiative to ask for help when needed, and is encouraged to do so more frequently in class. *N* is encouraged to always ask for clarification to ensure learning as well as making sure *P* finds out about any missed work.',
      'N-1': '*N* lacks the initiative to ask for help when needed, and frequently spends time off task rather than seeking any support or clarification from educators or peers. *N* is encouraged to always ask for clarification or further explanation to prioritize *P* success. Furthermore, *P* must ensure that *P* finds out about any missed work due to absences or disengagement.',
    },
    'Initiative - Taking Risks': {
      'E-1': '*N* is always willing to take risks and act on new ideas of *R* own or others. *P* actively seeks out challenges both academic and social and is happy to try new things. *N* will enthusiastically share new ideas with others and will approach opportunities to grow with a positive attitude.',
      'G-1': '*N* is willing to take risks and act on new ideas of *R* own or of close peers. *N* welcomes challenges both academic and social and is happy to try most new challenges. *N* will share new ideas with others and will often approach these opportunities with a positive attitude.',
      'S-1': '*N* is willing to take some risks and act on new ideas of *R* own. *P* accepts challenges in *R* academics but can be hesitant to try new things. *N* is encouraged to approach new tasks with a positive attitude and advocate for *H*self to achieve success.',
      'N-1': '*N* can be reluctant to take risks and act on new ideas. *H* accepts a few challenges with reinforcement but lacks confidence in these ventures. *N* is encouraged to approach new tasks with a positive attitude and advocate for *H*self to achieve success',
    },
    'Initiative - Self-Advocacy': {
      'E-1': '*N* is willing to self-advocate to ensure a full understanding of the material. *P* demonstrates an interest in learning beyond class expectations.',
      'G-1': '*N* is willing to self-advocate when necessary to ensure understanding of the material. *P* demonstrates an interest and curiosity in learning in all subject areas.',
      'S-1': '*N* is willing to self-advocate at times but is encouraged to ask for help whenever necessary. *P* demonstrates an interest in learning in favoured subject areas and is encouraged to extend this interest to other subjects.',
      'N-1': '*N* rarely self-advocates and is encouraged to ask for help whenever necessary to improve understanding. *P* demonstrates little interest in learning in most subject areas and is encouraged to find topics *P* is interested in.',
    },
    'Initiative - Tidy Spaces': {
      'E-1': '*R* own belongings and desk area are kept tidy and organized.  This means *N* is able to find the necessary materials quickly and begin work immediately.',
      'G-1': '*R* own belongings and desk area are kept tidy.  This means *N* is able to find the correct materials needed and begin work with minimal time wasted.',
      'S-1': '*R* own belongings and desk area are kept somewhat tidy without help. Improving this could help *N* find what *H* needs quickly.',
      'N-1': '*N* drastically needs to improve the tidiness and organization of *R* desk and work area. Working to improve this without reminders would help *N* find what *P* needs quickly and be able to get started on work or follow along with instructions on time.',
    },
    'Organization - Materials': {
      'E-1': '*N* is familiar with our classroom, where items go and where to find materials when needed. *P* always uses the most appropriate materials for tasks and returns them when finished in excellent condition.',
      'G-1': '*N* is familiar with our classroom, where items go and where to find materials when needed. *P* uses the appropriate materials for tasks and returns them when finished.',
      'S-1': '*N* is becoming familiar with our classroom, where items go and where to find materials when needed. *P* is starting to use the appropriate materials for tasks and return them when finished with fewer reminders.',
      'N-1': '*N* is still unfamiliar with our classroom, for example, where items go and where to find materials when needed. *P* often needs to be reminded to use the appropriate materials for tasks and return them when finished.',
    },
    'Organization - Desk': {
      'E-1': 'In addition, *R* own belongings and desk area are kept tidy and can be found easily.',
      'G-1': 'In addition, *R* own belongings and desk area are kept tidy.',
      'S-1': 'In addition, *R* own belongings and desk area are kept somewhat tidy. Improving this could help *N* find what *P* needs quickly.',
      'N-1': 'In addition, *N* needs to improve the tidiness and organization of *R* desk and work area. Working to improve this would help *N* find what *P* needs quickly and be able to get started on work sooner.',
    },
    'Organization - Time organization': {
      'E-1': '*N* organizes *R* time in class effectively to complete tasks. *P* knows what needs to be worked on and needs no help to achieve this.',
      'G-1': '*N* organizes *R* time in class independently to complete tasks. *P* knows what needs to be worked on and needs little help or reminders to achieve this.',
      'S-1': '*N* organizes *R* time in class with some success to complete tasks. *P* is encouraged to use the tools available to consider what tasks need to be worked on and then begin immediately.',
      'N-1': '*N* has difficulty organizing *R* time in class to complete tasks. *P* is encouraged to use the tools available to consider what tasks need to be done and then work to complete them without wasting time.',
    },
    'Organization - Manage priorities/organizers': {
      'E-1': '*N* is extremely well organized when completing tasks. *P* is able to establish priorities and manage time effectively, as well as use the most appropriate materials and organizational tools to complete tasks and achieve goals with great success.',
      'G-1': '*N* is well organized when completing tasks. *P* is able to establish priorities and manage time independently, as well as use the appropriate materials and organizational tools to complete tasks and achieve goals.',
      'S-1': '*N* is organized when completing tasks with some help. *P* is able to manage time with some success, as well as use the appropriate materials to complete tasks and achieve goals. It would be beneficial for *N* to use organizational tools such as agendas, table of contents and graphic organizers to help *H* organize *R* work. ',
      'N-1': '*N* finds remaining organized challenging when completing tasks. *P* needs assistance to manage *R* time and use the appropriate materials to complete tasks and achieve goals. It would be beneficial for *N* to use organizational tools such as agendas, table of contents and graphic organizers to help *H* organize *R* work.',
    },
    'Collaboration - Contribution': {
      'E-1': 'During collaborative activities, *N* is able to actively listen to others and respects their opinions. *P* actively participates in literacy and mathematical discussions in an appropriate manner, working well towards the successful completion of a shared task.',
      'G-1': 'During collaborative activities, *N* is able to listen to others and respects their opinions. *P* participates in literacy and mathematical discussions appropriately, working towards the successful completion of a shared task.',
      'S-1': 'During collaborative activities, *N* is willing to listen to others and usually respects their opinions. *P* participates in some discussions and activities with some prompting or sentence frames, infrequently contributing to a shared task. *N* is encouraged to voice *R* own ideas more and take a more active role in the group.',
      'N-1': 'During collaborative activities, *N* participates in group discussions. However, *P* has some difficulty listening to others and working in conjunction with the contributions of others. *N* is encouraged to keep an open mind and contribute.',
      'N-2': 'During collaborative activities, *N* has difficulty listening to others and respecting their opinions. *P* needs direct encouragement to participate appropriately in shared discussions and small group activities, at times hindering the successful completion of the task. *N* is encouraged to voice *R* own ideas more and take a more active role in the group.'
    },
    'Collaboration - Conflict': {
      'E-1': '*N* works very well with others, easily avoiding conflicts. *P* independently uses resolution strategies with success to help others solve problems and always looks for solutions that are positive for everyone involved.',
      'G-1': '*N* works well with others, avoiding conflicts and uses resolution strategies with success to solve problems when necessary. *P* tries to find solutions that are positive for everyone involved.',
      'S-1': '*N* generally works well with others and uses conflict resolution strategies with some success to solve problems. *P* is encouraged to look for solutions that are positive for everyone involved.',
      'N-1': '*N* finds it a challenge to work well with others and uses a few conflict resolution strategies with limited success to solve problems. *P* is encouraged to look for solutions that are positive for everyone involved.',
    },
    'Collaboration - Roles': {
      'E-1': 'When interacting with others, *N* works well in a variety of groupings, taking on different roles as needed and fulfilling *R* share of the work successfully. *N* is always fair and respectful to group members, often taking on a leadership role and helping those around *H*.',
      'G-1': 'When interacting with others, *N* works well in a variety of groupings, taking on different roles as needed and fulfilling *R* share of the work. *N* is fair and respectful to group members and will help those around *H* when necessary.',
      'S-1': 'When interacting with others, *N* works in a variety of groupings, taking on a few different roles as needed and fulfilling a share of the work. *P* is generally fair and respectful to group members. It would be helpful for *N* to listen carefully to the views of all group members and be willing to take on a wider variety of tasks.',
      'N-1': 'When interacting with others, *N* works well in limited groupings, taking on a few roles as needed and fulfilling a small share of the work. It would be helpful for *N* to listen carefully to the views of all group members and be respectful of various opinions.',
    },
    'Collaboration - Group Conflict': {
      'E-1': 'During collaborative activities, *N* is willing to accept any role necessary to complete the task successfully. *P* solves conflicts within the group to achieve a common goal.',
      'G-1': 'During collaborative activities, *N* is willing to accept most roles necessary to complete the task successfully. *P* works to solve conflicts within the group to achieve a common goal.',
      'S-1': `During collaborative activities, *N* is willing to accept a few different roles to complete the task successfully. *P* avoids conflicts but has difficulty solving them when they arise in order to achieve a common goal. *N* is encouraged to respond more positively to others' opinions and ideas.`,
      'N-1': `During collaborative activities, *N* will only accept a limited number of roles to complete the task successfully. *P* is often involved in conflicts within the group that work against the common goal. *N* is encouraged to respond more positively to others' opinions and ideas.`,
    },
    'Collaboration - Branching Out': {
      'E-1': 'When interacting with others, *N* shows respect to others’ ideas in an encouraging manner. *P* easily interacts with a wide variety of peers in positive ways in addition to *R* core group of friends.',
      'G-1': 'When interacting with others, *N* shows respect for others’ ideas. *P* has a core group of friends but happily interacts with a variety of other peers as well.',
      'S-1': `When interacting with others, *N* shows some respect for others' ideas although not consistently. *P* has a core group of friends but is encouraged to be more open to developing positive relationships with a wider variety of peers.`,
      'N-1': `When interacting with others, *N* does not always show respect to others' ideas. *P* is encouraged to develop more positive relationships with peers by listening to others' ideas and interests.`,
    },
    'Self-Regulation - Goal-Setting': {
      'E-1': '*N* always sets appropriate weekly goals for *H*self and works hard to achieve them. *P* works to reach *R* personal reading and writing goals, recognizing when *P* is successful.',
      'G-1': '*N* sets appropriate weekly goals for *H*self and works to achieve them. *P* works to reach *R* personal reading and writing goals during class activities.',
      'S-1': '*N* sets weekly goals for *H*self when reminded and works to achieve them. *P* is encouraged to focus on *R* personal reading and writing goals and recognize when *P* has been successful.',
      'N-1': '*N* will set simple weekly goals for *H*self with reminders but rarely works to achieve them. *P* is encouraged to focus on *R* personal reading and writing goals and recognize when *P* has been successful.',
    },
    'Self-Regulation - Perseverance': {
      'E-1': '*N* perseveres with a high level of effort when working on a challenging task. *P* is encouraged to identify personal strengths and weaknesses, and set goals to improve.',
      'G-1': '*N* is willing to persevere when working on a challenging task. *P* is encouraged to trust *R* own knowledge and have confidence in himself, only asking for help when necessary.',
      'S-1': '*N* can get discouraged when working on a challenging task. *P* is encouraged to listen attentively to instructions to promote the successful completion of activities.',
      'N-1': '*N* gets discouraged easily when working on a challenging task. *P* is encouraged to listen attentively to instructions to promote the successful completion of activities.',
    },
    'Self-Regulation - Reflection': {
      'E-1': '*N* constantly reflects upon *R* progress with an accurate view of *R* own successes and needs. *H* independently looks for ways to improve as a student and *P* works hard towards *R* goals.',
      'G-1': '*N* regularly reflects upon *R* progress with a fairly accurate view of *R* own successes and needs. *H* often looks for ways to improve as a student and *P* works towards *R* goals.',
      'S-1': '*N* reflects upon *R* progress when asked to and *R* view of *R* own successes and needs are somewhat realistic. *P* is encouraged to look for ways to improve as a student and work towards these goals.',
      'N-1': '*N* reflects upon *R* progress with guidance although *R* view of *R* own successes and needs can be inaccurate. *P* is encouraged to look for ways to improve as a student and work towards these goals.',
    },
    'Self-Regulation - Behaviours': {
      'E-1': '*N* is able to discern the appropriate time for certain behaviours (i.e., work times and play times) and always adheres to this. When working on a task, *N* takes an active role to find new ways to solve problems and persevere to completion.',
      'G-1': '*N* is able to discern the appropriate times for certain behaviours (i.e., work times and play times) and generally adheres to this.  When working on a task, *N* takes an active role in problem-solving and will persist with tasks.',
      'S-1': '*N* is encouraged to begin to discern the appropriate time for certain behaviours (i.e., work times and play times) and adhere to this. When working on a task or in the classroom, *N* is encouraged to persevere and look for new ways to solve problems before giving up.',
      'N-1': '*N* has difficulty discerning the appropriate time for certain behaviours (i.e., work times and play times) and regularly needs to be helped to remain on task. When working, *N* is encouraged to take an active role in classroom activities and persist with tasks.',
    },
    'Language': {
      'Progressing Very Well-1': '*N* demonstrates a clear understanding of reading and writing skills. *P* reads a variety of texts fluently, with accuracy, pacing and comprehension. *N* always generates ideas and organizes them well in multiple paragraph format. *P* is encouraged to continue to use technology to help enhance *R* writing and publishing skills this year in Grade 6!',
      'Progressing Well-1': '*N* is actively developing *R* knowledge and application of language skills at the Grade 6 level. *P* reads texts fluently with accuracy and comprehension at an appropriate pace. *N* generates ideas and organizes them in paragraph format with guidance. *N* is encouraged to keep up *R* efforts in class and use our class created success criteria to help *H* reflect on and revise *R* writing.',
      'Progressing Well-Low participation-1': '*N* is actively developing *R* knowledge and application of language skills at the Grade 6 level. *P* reads texts fluently with accuracy and comprehension at an appropriate pace. *N* generates ideas and organizes them in paragraph format with guidance. *N* is strongly encouraged to participate and use our class created success criteria to help *H* reflect on and revise *R* writing.',
      'Progressing Well-Missing deadlines-1': '*N* is actively developing *R* knowledge and application of language skills at the Grade 6 level. *P* reads texts fluently with accuracy and comprehension at an appropriate pace. *N* generates ideas and organizes them in paragraph format with guidance. *N* is strongly encouraged to participate, meet deadlines, and use both our class created success criteria and graphic organizers to help *H* reflect on and revise *R* writing.',
      'Progressing with Difficulty-Reading Only-1': 'Progressing with Difficulty-Reading Only',
      'Progressing with Difficulty- Word Study Only-1': '*N* demonstrates some difficulty reading grade-level texts aloud with fluency, expression and comprehension. *P* has demonstrated difficulty in spelling, word study, and the proper use of punctuation. With guidance in writing, *N* is able to generate and organize *R* creative ideas into graphic organizers and paragraph format. *N* is encouraged to continue engaging in explicit word study, and using technology to help enhance *R* writing and publishing skills this year in Grade 6!',
      'Progressing with Difficulty-Writing Only-1': '*N* demonstrates some understanding of reading and writing strategies. *N* has difficulty generating and organizing ideas into simple sentences, and benefits from the use of graphic organizers and direct one-on-one support when engaging in any writing process. *P* is able to generate ideas into sentences with the support of a scribe, and make meaningful personal connections to stories or texts that are read to *H*. *N* is encouraged to continue engaging in word study activities to build *H* reading confidence in common words, and using technology to support *H* writing process.',
      'Progressing with Difficulty-Reading and Writing IEP-1': '*N* demonstrates some understanding of reading and writing strategies. *N* has difficulty generating and organizing ideas into simple sentences, and benefits from the use of graphic organizers and direct one-on-one support when engaging in any writing process. *P* is able to generate ideas into sentences with the support of a scribe, and make meaningful personal connections to stories or texts that are read to *H*. *N* is encouraged to continue engaging in word study activities to build *H* reading confidence in common words, and using technology to support *H* writing process.',
      'Progressing Well - IEP-1': '*N* demonstrates a growing understanding of reading and writing strategies. *N* has success organizing ideas into simple sentences with the use of technology, drawings, and graphic organizers. Direct support is essential to *P* ability to engage in any editing or revision processes when writing. *N* is able to generate ideas orally and make personal connections to stories or texts that are read to *H*. *N* is encouraged to continue engaging in word study activities to build *H* reading confidence in common words, and using technology to support *H* writing process.'
    },
    'MATHEMATICS (NUMBER SENSE)': {
      'Progressing Very Well-1': '*N* is an active contributor to math talks and lessons. *P* demonstrates significant understanding of math concepts taught so far and an ability to rise to mathematical challenges. In number sense, *N* demonstrates critical thinking with a high degree of effectiveness.*N* is encouraged to engage in review games to solidify and retain new learning.',
      'Progressing Well-1': '*N* is progressing well in the grade 6 math program and demonstrates an understanding of math concepts taught so far with considerable effectiveness. In order to progress well towards the term expectations, *P* is encouraged to engage in regular math routines to fill any gaps in new learning and play curriculum-based review games at home in order to exercise mental math skills, and retain essential number sense concepts.',
      'Progressing With Difficulty-1': '*N* is beginning to develop some understanding of math concepts taught so far. In number sense, *N* is encouraged to ask questions and use resources available to *H* in order to establish an essential foundation of mathematical concepts. *N* is encouraged to share ideas and engage actively in math talks as well as review number operations in everyday contexts. *N* is strongly encouraged to develop a math practice routine at home through curriculum-based games to solidify this essential mathematical foundation for Grade 6.',
    }
  }
} as const;

export type CommentBank = typeof commentBank;